services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wedding
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: wedding
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - db

volumes:
  db_data:
