services:
  db:
    image: postgres:15
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app          
    working_dir: /app      
    environment:
      - PYTHONPATH=/app      
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  db_data:

