"""add plus_ones table and link to users

Revision ID: 2a05c3bf9fea
Revises: c7614ddd7510
Create Date: 2025-05-11 06:36:26.325416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a05c3bf9fea'
down_revision: Union[str, None] = 'c7614ddd7510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plus_ones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('dietary_restrictions', sa.String(), nullable=True),
    sa.Column('appetizer_option_id', sa.Integer(), nullable=True),
    sa.Column('main_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appetizer_option_id'], ['dinner_options.id'], ),
    sa.ForeignKeyConstraint(['main_option_id'], ['dinner_options.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_plus_ones_id'), 'plus_ones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plus_ones_id'), table_name='plus_ones')
    op.drop_table('plus_ones')
    # ### end Alembic commands ###
