"""create users table

Revision ID: 5111c10be850
Revises: b5fc1ed5b6d4
Create Date: 2025-05-07 07:56:28.163665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5111c10be850'
down_revision: Union[str, None] = 'b5fc1ed5b6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dinner_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('appetizer', 'entree', name='dinnercategory'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dinner_options_category'), 'dinner_options', ['category'], unique=False)
    op.create_index(op.f('ix_dinner_options_id'), 'dinner_options', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('rsvp_confirmed', sa.Boolean(), nullable=False),
    sa.Column('dietary_restrictions', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('appetizer_option_id', sa.Integer(), nullable=True),
    sa.Column('main_option_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['appetizer_option_id'], ['dinner_options.id'], ),
    sa.ForeignKeyConstraint(['main_option_id'], ['dinner_options.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_dinner_options_id'), table_name='dinner_options')
    op.drop_index(op.f('ix_dinner_options_category'), table_name='dinner_options')
    op.drop_table('dinner_options')
    # ### end Alembic commands ###
